# Generated by Django 3.0.3 on 2020-02-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastRoast',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('boast_or_roast', models.BooleanField(
                    choices=[(1, 'Roast'), (2, 'Boast')], default=1)),
                ('content', models.CharField(max_length=280)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
