# Generated by Django 3.0.3 on 2020-02-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastroast',
            name='boast_or_roast',
        ),
        migrations.AddField(
            model_name='boastroast',
            name='boast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boastroast',
            name='roast',
            field=models.BooleanField(default=True),
        ),
    ]
