# Generated by Django 3.0.3 on 2020-02-10 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost', '0003_auto_20200210_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastroast',
            old_name='downvote',
            new_name='upordown',
        ),
        migrations.RemoveField(
            model_name='boastroast',
            name='roast',
        ),
        migrations.RemoveField(
            model_name='boastroast',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='boastroast',
            name='boast',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='boastroast',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
