# Generated by Django 3.0.3 on 2020-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost', '0007_auto_20200210_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroast',
            name='post_key',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
