# Generated by Django 3.0.3 on 2020-02-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost', '0008_boastroast_post_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastroast',
            name='post_key',
        ),
    ]
